spring:
  datasource:
    hikari:
      jdbc-url: jdbc:h2:file:./data/demo;AUTO_SERVER=TRUE
      username: sa
      password:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true